<%
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
rerun_opts = rerun.to_s.strip.empty? ? "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} features" : "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} #{rerun}"
std_opts = "--format #{ENV['CUCUMBER_FORMAT'] || 'Cucumber::Formatter::Fuubar'} --strict --tags ~@wip --tags ~@javascript"
%>
default: --drb <%= std_opts %> features
wip: --drb --tags @wip:4 --wip features --tags ~@javascript
rerun: --drb <%= rerun_opts %> --format rerun --out rerun.txt --strict --tags ~@wip
js: --tags @javascript --format pretty features
wipjs: --tags @javascript  --tags @wip:4 --wip features
guard: --format Cucumber::Formatter::Fuubar --strict --tags ~@wip --tags ~@javascript --drb
